name: Deploy to Azure Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'appsettings.json'
      env:
        ServiceBus.ConnectionString: ${{ secrets.SERVICE_BUS_CONNECTION_STRING }}
        Spotify.ClientSecret: ${{ secrets.SPOTIFY_CLIENTSECRET }}
        Spotify.ClientId: ${{ secrets.SPOTIFY_CLIENTID }}
    - name: Login to azure
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build image
      run: |
        docker build -t contoso.azurecr.io/koala-activity-music-handler-service:${{ github.sha }} .
        docker tag contoso.azurecr.io/koala-activity-music-handler-service:${{ github.sha }} contoso.azurecr.io/koala-activity-music-handler-service:latest
    - name: Push image
      run: |
        docker push ${{ secrets.LOGIN_SERVER }}/koala-activity-music-handler-service:latest
        docker push ${{ secrets.LOGIN_SERVER }}/koala-activity-music-handler-service:${{ github.sha }}
